framework:
    translator: { fallbacks: [ "en" ] }

artgris_file_manager:
    web_dir: public                 # set your public Directory (not required, default value: web)
    conf:
        default:
            dir: "../public/uploads"
            view: 'thumbnail'
            upload:
                image_library: 0
                image_versions: {'full': {}, '': {max_width: 1500, max_height: 1500}, }